sonar.projectKey=jls42_ai-powered-markdown-translator
sonar.organization=jls42

sonar.projectName=ai-powered-markdown-translator
sonar.projectVersion=1.0

sonar.sources=translate.py,scripts
sonar.tests=tests,scripts/tests
sonar.python.version=3.10,3.11,3.12

sonar.python.coverage.reportPaths=coverage.xml

sonar.exclusions=venv/**,**/__pycache__/**,traductions_*/**,README-*.md,CHANGELOG-*.md,translate.py.old,exemple.txt
sonar.test.inclusions=tests/**,scripts/tests/**

sonar.sourceEncoding=UTF-8
